/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CodigosDeFuncionamiento.*;

/**
 * Ventana de la carrera
 * 
 * @author Rafael Navarro Prieto
 * @version 1.0
 */
public class Coches extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Ventana principal
	 */
	public Minijuegos ventanaPrincipal;
	/**
	 * Hilo del primer coche
	 */
	Thread coche1;
	/**
	 * Hilo del segundo coche
	 */
	Thread coche2;

	/**
	 * Creates new form Test
	 */
	public Coches(Minijuegos aThis) {
		initComponents();
		ventanaPrincipal = aThis;
		setEnabled(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		barraCoche1 = new javax.swing.JProgressBar();
		barraCoche2 = new javax.swing.JProgressBar();
		boton = new javax.swing.JButton();
		cochePrimero = new javax.swing.JLabel();
		cocheSegundo = new javax.swing.JLabel();
		carretera = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Carrera de cohes");
		setEnabled(false);
		setMaximumSize(null);
		setMinimumSize(null);
		setPreferredSize(new java.awt.Dimension(900, 475));
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Jugador 1");

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("Jugador 2");

		barraCoche1.setMaximum(800);

		barraCoche2.setMaximum(800);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(58, 58, 58)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																barraCoche1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																300,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																barraCoche2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																300,
																Short.MAX_VALUE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(98, 98, 98)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				barraCoche1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				38,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(1,
																				1,
																				1)
																		.addComponent(
																				barraCoche2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				27,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(24, Short.MAX_VALUE)));

		getContentPane().add(
				jPanel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 700,
						90));

		boton.setText("Iniciar carrera");
		boton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonActionPerformed(evt);
			}
		});
		getContentPane().add(
				boton,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380,
						460, 50));

		cochePrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagenes/cochefinal.png"))); // NOI18N
		cochePrimero.setText("jLabel1");
		getContentPane().add(
				cochePrimero,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170,
						-1));

		cocheSegundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagenes/cochefinal.png"))); // NOI18N
		cocheSegundo.setText("jLabel2");
		getContentPane().add(
				cocheSegundo,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170,
						-1));

		carretera.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/imagenes/carretera.png"))); // NOI18N
		carretera.setMaximumSize(null);
		carretera.setMinimumSize(null);
		carretera.setPreferredSize(new java.awt.Dimension(500, 7717));
		getContentPane().add(
				carretera,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900,
						450));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void botonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonActionPerformed
		boton.setVisible(false);
		coche1 = new Coche("Jugador 1", 800, cochePrimero, barraCoche1,
				(int) (Math.random() * 50 + 1));
		coche2 = new Coche("Jugador 2", 800, cocheSegundo, barraCoche2,
				(int) (Math.random() * 50 + 1));
		coche1.start();
		coche2.start();
		Thread meta = new meta("meta", coche1, coche2, ventanaPrincipal, this);
		meta.start();
	}// GEN-LAST:event_botonActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		cerrar();
	}// GEN-LAST:event_formWindowClosing

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JProgressBar barraCoche1;
	private javax.swing.JProgressBar barraCoche2;
	private javax.swing.JButton boton;
	private javax.swing.JLabel carretera;
	private javax.swing.JLabel cochePrimero;
	private javax.swing.JLabel cocheSegundo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;

	// End of variables declaration//GEN-END:variables

	/**
	 * Acciones que se realizan antes de cerrar la ventana
	 * 
	 * @return devuelve -1
	 */
	private int cerrar() {
		dispose();
		ventanaPrincipal.setVisible(true);
		ventanaPrincipal.toFront();
		return -1;
	}

}
